/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Sistema_control;

import java.sql.PreparedStatement;
import javax.swing.JOptionPane;

/**
 *
 * @author Brisfer
 */
public class Consulta extends javax.swing.JFrame {

    Conexion conectaMysql;
    String fecha, observacion;
    int clave;

    /**
     * Creates new form Consulta
     */
    public Consulta() {
        initComponents();
        conectaMysql = new Conexion();
        conectaMysql.conectar();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txt_fecha = new javax.swing.JTextField();
        txt_observaciones = new javax.swing.JTextField();
        txt_clave = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txt_fecha.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_fecha.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txt_fecha, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 80, 180, 30));

        txt_observaciones.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_observaciones.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(41, 43, 45)), "observaciones", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.DEFAULT_POSITION));
        getContentPane().add(txt_observaciones, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 140, 520, 290));

        txt_clave.setFont(new java.awt.Font("Times New Roman", 0, 14)); // NOI18N
        txt_clave.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        getContentPane().add(txt_clave, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 40, 180, 30));

        jButton1.setFont(new java.awt.Font("Adobe Heiti Std R", 1, 24)); // NOI18N
        jButton1.setText("Guardar");
        jButton1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 460, 110, 40));

        jLabel4.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel4.setText("Fecha");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 70, -1));

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/pie.png"))); // NOI18N
        jLabel3.setText("jLabel3");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 10, 160, 160));

        jLabel2.setFont(new java.awt.Font("Baskerville Old Face", 1, 24)); // NOI18N
        jLabel2.setText("Clave del paciente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 210, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/1.png"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 678, 511));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (!txt_clave.getText().isEmpty() && !txt_observaciones.getText().isEmpty() && !txt_fecha.getText().isEmpty()) {
            Buscar(clave, fecha, observacion);
        } else {
            JOptionPane.showMessageDialog(this, "no debe haber capos vacios");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Consulta.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Consulta().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JTextField txt_clave;
    private javax.swing.JTextField txt_fecha;
    private javax.swing.JTextField txt_observaciones;
    // End of variables declaration//GEN-END:variables

    private void Buscar(int clave, String fecha, String observacion) {
        clave = Integer.parseInt(txt_clave.getText());
        fecha = txt_fecha.getText();
        observacion = txt_observaciones.getText();
        try {
            String sql = "INSERT INTO consul VALUES (?,?,?)";
            PreparedStatement sentencia = conectaMysql.miConexion.prepareStatement(sql);
            sentencia.setInt(1, clave);
            sentencia.setString(2, observacion);
            sentencia.setString(3, fecha);
            sentencia.execute();
            sentencia.close();
            JOptionPane.showMessageDialog(this, "Registro exitoso");
            limpiar();
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(this, "Erro" + ex.getMessage() + "No se pudo registrar");
        }
        
        
//       try {
//            String sql = "UPDATE consul SET fecha_con='"+fecha+"',texto='"+observacion+"' WHERE id_paciente="+clave;
//            PreparedStatement sentencia = conectaMysql.miConexion.prepareStatement(sql);
//            sentencia.execute();
//            sentencia.close(); 
//            JOptionPane.showMessageDialog(this, "Registro Actualizado");
//           
//        } catch (Exception ex) {
//            JOptionPane.showMessageDialog(this, "Erro" + ex.getMessage() + "No se pudo registrar");
//        } 
        
        
        
        
    }

    private void limpiar() {
        txt_clave.setText("");
        txt_fecha.setText("");
        txt_observaciones.setText("");
    }
}
